IntDiv=0
IntMul=1
IntSub=2
IntAdd=3
PrintI=4
WindowsExit=5
B=6
Bo=7
Boo=8
Bool=9
BoolN=10
BoolNo=11
BoolNot=12
Print=13
PrintB=14
I=15
In=16
Int=17
IntL=18
IntLE=19
IntLe=20
IntLT=21
IntT=22
IntGT=23
IntG=24
IntE=25
IntGE=26
IntEQ=27
IntNEQ=28
IntNE=29
